### ISSUE TITLE
Interface d'administration

### ISSUE THREAD

**Issue by W95Psp** [W95Psp/InterfaceWebProjetL2#21]
# Déjà

Il y a deux personnes qui lisent et notent le rapport : 
- L'encadrant du sujet (:-1: Problème : il peut y avoir plusieurs encadrants !) 
- Un enseignant autre, désigné par l'administrateur (Est-ce que cet autre enseignant doit être dans le jury ?)
  Problème : note individuelle (par élève) ou note globale de groupe ? Si ça dépend, lesquelles, comment ? (Il me semble que l'on en avait parlé mais je ne retrouve aucune trace)

Il y a un jury présentation à l'oral, qui noterons suivant divers critères le travail des élèves indépendamment.

Pour les critères, ils sont modifiable lorsque aucun projet n'est affecté.
# Todo
- [ ] Si l'administrateur veut assigner les deux profs qui notent le rapport, il peut aller dans l'onglet groupes de la page d'administration, ou aller sur la page de projet concerné, en mode édition
- [ ] Si l'administrateur veut assigner le jury, il peut se rendre onglet groupes / page projet mode edition
- [ ] Réaliser l'interface de modification de critères de notations
